version: '3.1'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"


