// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: gym.proto

package proto_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdministratorV1Client is the client API for AdministratorV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdministratorV1Client interface {
	CreateMembership(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type administratorV1Client struct {
	cc grpc.ClientConnInterface
}

func NewAdministratorV1Client(cc grpc.ClientConnInterface) AdministratorV1Client {
	return &administratorV1Client{cc}
}

func (c *administratorV1Client) CreateMembership(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.AdministratorV1/CreateMembership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdministratorV1Server is the server API for AdministratorV1 service.
// All implementations must embed UnimplementedAdministratorV1Server
// for forward compatibility
type AdministratorV1Server interface {
	CreateMembership(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedAdministratorV1Server()
}

// UnimplementedAdministratorV1Server must be embedded to have forward compatible implementations.
type UnimplementedAdministratorV1Server struct {
}

func (UnimplementedAdministratorV1Server) CreateMembership(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembership not implemented")
}
func (UnimplementedAdministratorV1Server) mustEmbedUnimplementedAdministratorV1Server() {}

// UnsafeAdministratorV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdministratorV1Server will
// result in compilation errors.
type UnsafeAdministratorV1Server interface {
	mustEmbedUnimplementedAdministratorV1Server()
}

func RegisterAdministratorV1Server(s grpc.ServiceRegistrar, srv AdministratorV1Server) {
	s.RegisterService(&AdministratorV1_ServiceDesc, srv)
}

func _AdministratorV1_CreateMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdministratorV1Server).CreateMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AdministratorV1/CreateMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdministratorV1Server).CreateMembership(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdministratorV1_ServiceDesc is the grpc.ServiceDesc for AdministratorV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdministratorV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AdministratorV1",
	HandlerType: (*AdministratorV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMembership",
			Handler:    _AdministratorV1_CreateMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gym.proto",
}
